// Country data with codes for lifespan calculation
class CountryData {
  final String name;
  final String code;
  
  const CountryData(this.name, this.code);
}

const List<CountryData> countries = [
  CountryData('United States', 'US'),
  CountryData('Canada', 'Canada'),
  CountryData('United Kingdom', 'UK'),
  CountryData('Australia', 'Australia'),
  CountryData('Germany', 'Germany'),
  CountryData('France', 'France'),
  CountryData('Japan', 'Japan'),
  CountryData('South Korea', 'South Korea'),
  CountryData('China', 'China'),
  CountryData('India', 'India'),
  CountryData('Brazil', 'Brazil'),
  CountryData('Mexico', 'Mexico'),
  CountryData('Russia', 'Russia'),
  CountryData('Nigeria', 'Nigeria'),
  CountryData('Egypt', 'Egypt'),
  CountryData('South Africa', 'South Africa'),
  CountryData('Italy', 'Italy'),
  CountryData('Spain', 'Spain'),
  CountryData('Netherlands', 'Netherlands'),
  CountryData('Sweden', 'Sweden'),
  CountryData('Norway', 'Norway'),
  CountryData('Denmark', 'Denmark'),
  CountryData('Finland', 'Finland'),
  CountryData('Switzerland', 'Switzerland'),
  CountryData('Austria', 'Austria'),
  CountryData('Belgium', 'Belgium'),
  CountryData('Ireland', 'Ireland'),
  CountryData('New Zealand', 'New Zealand'),
  CountryData('Singapore', 'Singapore'),
  CountryData('Hong Kong', 'Hong Kong'),
  CountryData('Taiwan', 'Taiwan'),
  CountryData('Thailand', 'Thailand'),
  CountryData('Vietnam', 'Vietnam'),
  CountryData('Malaysia', 'Malaysia'),
  CountryData('Indonesia', 'Indonesia'),
  CountryData('Philippines', 'Philippines'),
  CountryData('Pakistan', 'Pakistan'),
  CountryData('Bangladesh', 'Bangladesh'),
  CountryData('Sri Lanka', 'Sri Lanka'),
  CountryData('Nepal', 'Nepal'),
  CountryData('Myanmar', 'Myanmar'),
  CountryData('Cambodia', 'Cambodia'),
  CountryData('Laos', 'Laos'),
  CountryData('Mongolia', 'Mongolia'),
  CountryData('Kazakhstan', 'Kazakhstan'),
  CountryData('Uzbekistan', 'Uzbekistan'),
  CountryData('Kyrgyzstan', 'Kyrgyzstan'),
  CountryData('Tajikistan', 'Tajikistan'),
  CountryData('Turkmenistan', 'Turkmenistan'),
  CountryData('Azerbaijan', 'Azerbaijan'),
  CountryData('Georgia', 'Georgia'),
  CountryData('Armenia', 'Armenia'),
  CountryData('Ukraine', 'Ukraine'),
  CountryData('Belarus', 'Belarus'),
  CountryData('Moldova', 'Moldova'),
  CountryData('Romania', 'Romania'),
  CountryData('Bulgaria', 'Bulgaria'),
  CountryData('Serbia', 'Serbia'),
  CountryData('Croatia', 'Croatia'),
  CountryData('Slovenia', 'Slovenia'),
  CountryData('Slovakia', 'Slovakia'),
  CountryData('Czech Republic', 'Czech Republic'),
  CountryData('Poland', 'Poland'),
  CountryData('Hungary', 'Hungary'),
  CountryData('Estonia', 'Estonia'),
  CountryData('Latvia', 'Latvia'),
  CountryData('Lithuania', 'Lithuania'),
  CountryData('Greece', 'Greece'),
  CountryData('Portugal', 'Portugal'),
  CountryData('Turkey', 'Turkey'),
  CountryData('Israel', 'Israel'),
  CountryData('Lebanon', 'Lebanon'),
  CountryData('Jordan', 'Jordan'),
  CountryData('Syria', 'Syria'),
  CountryData('Iraq', 'Iraq'),
  CountryData('Iran', 'Iran'),
  CountryData('Afghanistan', 'Afghanistan'),
  CountryData('Brunei', 'Brunei'),
  CountryData('East Timor', 'East Timor'),
  CountryData('Papua New Guinea', 'Papua New Guinea'),
  CountryData('Fiji', 'Fiji'),
  CountryData('Vanuatu', 'Vanuatu'),
  CountryData('Solomon Islands', 'Solomon Islands'),
  CountryData('New Caledonia', 'New Caledonia'),
  CountryData('French Polynesia', 'French Polynesia'),
  CountryData('Samoa', 'Samoa'),
  CountryData('Tonga', 'Tonga'),
  CountryData('Kiribati', 'Kiribati'),
  CountryData('Tuvalu', 'Tuvalu'),
  CountryData('Nauru', 'Nauru'),
  CountryData('Marshall Islands', 'Marshall Islands'),
  CountryData('Micronesia', 'Micronesia'),
  CountryData('Palau', 'Palau'),
  CountryData('Guam', 'Guam'),
  CountryData('Northern Mariana Islands', 'Northern Mariana Islands'),
  CountryData('American Samoa', 'American Samoa'),
  CountryData('Cook Islands', 'Cook Islands'),
  CountryData('Niue', 'Niue'),
  CountryData('Tokelau', 'Tokelau'),
  CountryData('Wallis and Futuna', 'Wallis and Futuna'),
  CountryData('Pitcairn', 'Pitcairn'),
];

const List<String> genders = ['Male', 'Female'];

const List<String> smokingOptions = ['Never smoked', 'Former smoker', 'Current smoker', 'Occasional smoker'];

const List<String> exerciseOptions = ['Sedentary (no exercise)', 'Light (1-2 days/week)', 'Moderate (3-4 days/week)', 'Active (5-6 days/week)', 'Very active (daily exercise)'];

const List<String> alcoholOptions = ['Never', 'Rarely (1-2 times/month)', 'Occasionally (1-2 times/week)', 'Regularly (3-4 times/week)', 'Frequently (daily)']; 